version: '3.9'

services:
    db:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=accomodationdb'
            - 'POSTGRES_PASSWORD=password'
            - 'POSTGRES_USER=postgres'
        ports:
            - '5432:5432'
        networks:
            - mynetwork
      
    pgadmin:
        image: 'dpage/pgadmin4:latest'
        environment:
          - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
          - 'PGADMIN_DEFAULT_PASSWORD=password'
        ports:
          - '5050:80'
        depends_on:
          - postgres
        networks:
          - mynetwork
          
    app:
        image: accomodation_service_image
        depends_on:
          - db
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accomodationdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
        ports:
          - "8080:8080"
        networks:
          - mynetwork
          
networks:
  mynetwork: